spring:
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: always
springdoc:
  swagger-ui:
    disable-swagger-default-url: true